cameras:

  camera_front:
    device_id: 0
    frame_id: camera_front
    topic: /camera/front/image_raw
    fps: 30

  camera_rear:
    device_id: 1
    frame_id: camera_rear
    topic: /camera/rear/image_raw
    fps: 30

  camera_left:
    device_id: 2
    frame_id: camera_left
    topic: /camera/left/image_raw
    fps: 30

  camera_right:
    device_id: 3
    frame_id: camera_right
    topic: /camera/right/image_raw
    fps: 30